[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
time_vault = "8drWJPiyFu9CtzbH3p1oK4iQG5HKGR6Cx3ReKDoPSThh"

[programs.localnet]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devkey-bytes.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
